- name: install and start Nginx
  hosts: web
  become: yes
  tasks:
    - name: installing Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes