- name: data types
  hosts: local
  vars:
    course: "Devops with AWS" # String
    Tools: # list
    - linux
    - terraform
    - docker
    Experience: # map or dictionary
      DevOps: 3
      AWS : 2
      Docker: 1
    RealProject: true #boolean
    tasks:
      - name: print variables
        ansible.builtin.debug:
          msg: "Course is {{course}}, Tools covered {{Tools}}, Experience is {{Experience}}, is it real project: {{RealProject}}"