- name: Advanced loops
  hosts: local
  become: true
  tasks:
    - name: install/uninstall packages
      ansible.builtin.dnf:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - { name: 'postfix' , state: 'absent' }
        - { name: 'fail2ban' , state: 'absent'}
        - { name: 'nginx' , state: 'absent' }
        - { name: 'nodejs' , state: 'present'}